#!/bin/bash
replace '(?!")(\w+):(?!")' '"$1":' $1 >> /dev/null
replace '(")(http)(s*)"' 'http$3' $1 >> /dev/null
replace '(})(\).call\(this\);)' '' $1 >> /dev/null
replace '(})(\);)' '}' $1  >> /dev/null
replace '(\(function\(\) {)' ' ' $1 >> /dev/null
replace '(\({)' '{' $1 >> /dev/null
replace  '// Generated by CoffeeScript 1.3.1' '' $1 >> /dev/null
sed '/^$/d' $1 > $2
rm $1
jsonlint $2 1>&2
